import { NewspaperData } from './types';

export const PRESET_TEMPLATES: Record<string, { name: string; description: string; data: NewspaperData }> = {
  standard: {
    name: '日刊デイリー新聞（標準）',
    description: '本格的な日刊紙スタイル。総合ニュース、社説風コラム、天気予報',
    data: {
      paperTitle: 'デイリー日報',
      issueNumber: '第 24,801 号',
      edition: '朝刊',
      publishDate: '2026年 10月 2日（金曜日）',
      price: '定価 160円 (本体145円)',
      publisher: 'デイリー日報社 東京本社',
      slogan: '確かな視点、日々の鼓動を届ける総合紙',
      weather: {
        weather: 'sunny',
        maxTemp: 24,
        minTemp: 16,
        phrase: '秋晴れの心地よい一日。洗濯日和。',
      },
      leadArticle: {
        id: 'lead-1',
        category: 'トップニュース',
        headline: '秋の味覚フェス、過去最多の来場者を記録！',
        subHeadline: '地元の秋刀魚や新米を求め大盛況',
        author: '特派員 櫻井',
        content: `秋晴れに恵まれた週末、市中央公園にて開催された「秋の味覚フェスティバル」は、開始早々から大勢の家族連れや食通らで賑わいを見せた。\n\n目玉となった炭火焼き秋刀魚のブースには開場前から数百メートルの行列ができ、香ばしい煙とともに秋の訪れを五感で楽しむ姿があちこちで見られた。主催者発表によると、来場者数は前年比約二割増の五万人を突破し、過去最高を大幅に更新した。\n\n実行委員長は「多くの笑顔が見られて感無量。地域活性化の大きな一歩になった」と語り、来年のさらなる拡充を約束した。`,
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        imageCaption: '▲ 炭火で豪快に焼かれる旬の秋刀魚と賑わう来場者',
        direction: 'vertical',
      },
      subArticle1: {
        id: 'sub-1',
        category: '地域・文化',
        headline: '路地裏の老舗喫茶店、創業半世紀の珈琲哲学',
        subHeadline: '変わらぬ一杯が紡ぐ街の記憶',
        author: '文化部 記者',
        content: `駅前の喧騒を抜けた小道に佇む喫茶「琥珀」。真鍮のドアノブを回すと、深煎り豆の芳醇なアロマと振り子時計の刻む音が静かに迎えてくれる。\n\n今年で創業五十周年を迎えたマスターは、「流行は移り変わるが、人が一息つきたい場所の温もりはいつの時代も同じ」と微笑む。今日も常連客が静かにページをめくっている。`,
        imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=80',
        imageCaption: '▲ ネルドリップで丁寧に点てられる至福の一杯',
        direction: 'vertical',
      },
      subArticle2: {
        id: 'sub-2',
        category: '暮らし',
        headline: '街角図書館「ひとやすみ文庫」がオープン',
        subHeadline: '誰でも寄贈・貸出できる憩いの本棚',
        author: '社会部',
        content: `商店街の空きスペースを活用した無人図書コーナー「ひとやすみ文庫」が設置され、早くも住民の交流拠点として好評を博している。誰でも一冊持ち寄り、一冊借りられる仕組みだ。`,
        direction: 'vertical',
      },
      columnCorner: {
        title: '春秋コラム',
        author: '論説委員',
        content: `空が高く澄み渡る季節となった。ふと道端に目を向けると、小さなコスモスが風に揺れている。あわただしい日常のなかで、季節の歩みに耳を澄ます余裕を忘れずにいたいものだ。文字の向こうに広がる景色を、今日も丁寧に記録し届けていきたい。`,
      },
      fourKomaTitle: 'きょうのひとコマ',
      fourKomaFrames: [
        { caption: '① 朝の挨拶', text: '「おはよう！」元気な声がこだまする。' },
        { caption: '② 二度寝の罠', text: '布団の温もりが引き止める…' },
        { caption: '③ 電車ダッシュ', text: 'あと3分！奇跡の滑り込み成功。' },
        { caption: '④ 到着', text: 'なんと始業10分前！充実の金曜日。' },
      ],
      horoscope: [
        { sign: '牡羊座', luck: '★★★★★', advice: 'ひらめきを行動に移すと大吉。ラッキー色は茜色。' },
        { sign: '獅子座', luck: '★★★★☆', advice: '周囲への感謝の言葉が幸運を呼び込む。' },
        { sign: '射手座', luck: '★★★★☆', advice: '散歩道で新しい発見あり。珈琲ブレイク推奨。' },
      ],
      adText: {
        sponsor: '創業百年 誠心文具堂',
        catchphrase: '手書きの温もりを、大切な人へ。',
        subtext: '特製万年筆＆高級万年筆インク 秋の特別感謝セール開催中！',
      },
      theme: 'retro',
      isGogai: false,
      fontStyle: 'mincho',
    },
  },

  gogai: {
    name: '速報！号外スクープ新聞',
    description: 'インパクト抜群の「号外」大見出し。事件、合格発表、重大発表に最適！',
    data: {
      paperTitle: 'デイリー日報',
      issueNumber: '号外',
      edition: '号外特別版',
      publishDate: '2026年 10月 2日 緊急発行',
      price: '臨時無料配布',
      publisher: 'デイリー日報社 報道局特報班',
      slogan: '歴史が動いた瞬間をリアルタイムで速報',
      weather: {
        weather: 'sunny',
        maxTemp: 28,
        minTemp: 19,
        phrase: '熱気冷めやらぬ劇的な青空！',
      },
      leadArticle: {
        id: 'lead-gogai',
        category: '超特報',
        headline: 'ついに快挙達成！奇跡の大逆転勝利！',
        subHeadline: '最後まで諦めぬ執念が実を結ぶ / 全米が、いや日本中が沸いた',
        author: '特報速報部',
        content: `本日午後、全世界が固唾をのんで見守るなか、劇的な展開により見事な目標達成を果たした！\n\n一時は絶望的とみられた劣勢を跳ね返し、最後の一瞬で見せた超人的な集中力は、集まった観衆のみならず世界中の人々へ深い感動と勇気を与えた。\n\n関係者は涙ながらに「信じ続けてくれた皆のおかげ」と語り、会場は割れんばかりの拍手と歓声に包まれた。歴史に深く刻まれる記念すべき一日となった。`,
        imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=600&q=80',
        imageCaption: '▲ 劇的勝利の瞬間に歓喜の雄叫びをあげる瞬間',
        direction: 'vertical',
      },
      subArticle1: {
        id: 'sub-gogai-1',
        category: '現場の声',
        headline: '街頭インタビュー「本当に鳥肌が立ちました」',
        subHeadline: '渋谷・新宿など各地で号外を求める長蛇の列',
        author: '社会部特派員',
        content: `号外の配布が始まると、駅前広場には一瞬で人垣ができた。手にした人々は歓声を上げ、スマートフォンで記念撮影をする姿が目立った。「勇気をもらいました。明日から自分も頑張れそう」と笑顔を弾けさせた。`,
        direction: 'vertical',
      },
      subArticle2: {
        id: 'sub-gogai-2',
        category: '分析',
        headline: '勝因は日々の地道な積み重ね',
        subHeadline: '専門家も絶賛「準備の質が違った」',
        author: '解説主幹',
        content: `奇跡のように見えた一撃だが、関係者によれば数年にわたる徹底した準備と地道な練習の積み重ねが生んだ必然の勝利だった。`,
        direction: 'vertical',
      },
      columnCorner: {
        title: '特報寸評',
        author: 'デスク',
        content: `人は奇跡と呼ぶかもしれない。だがそこに至る無数の流した汗と涙を知る者には、これは正当な努力への祝福に見える。今宵は美酒に酔いしれよう。`,
      },
      fourKomaTitle: '号外速報裏話',
      fourKomaFrames: [
        { caption: '① 緊迫の瞬間', text: '息をのむオフィス一同。' },
        { caption: '② 歓喜爆発', text: '「やったーーー！！」天井に頭をぶつける。' },
        { caption: '③ 印刷機フル回転', text: 'インクの匂いと轟音が走る！' },
        { caption: '④ 街頭へダッシュ', text: '号外を配る手も震えるほどの感動！' },
      ],
      horoscope: [
        { sign: '全星座', luck: '★★★★★', advice: '今夜はお祝い！好きなものを思いっきり食べて祝杯をあげよう。' },
      ],
      adText: {
        sponsor: '祝賀特売実行委員会',
        catchphrase: '歴史的快挙を祝して！全品特別ポイント10倍セール！',
        subtext: '今週末限定・店舗＆オンラインストア同時開催中',
      },
      theme: 'gogai',
      isGogai: true,
      fontStyle: 'mincho',
    },
  },

  school: {
    name: '学級新聞・学校新聞（クラス通信）',
    description: '学校の行事、合唱コンクール、運動会、遠足などの思い出記録に',
    data: {
      paperTitle: 'たいよう組 学級新聞',
      issueNumber: '第 12 号',
      edition: '秋の特別号',
      publishDate: '2026年 10月 2日 発行',
      price: '無料配布 (みんなの宝物)',
      publisher: 'たいよう組 新聞係一同',
      slogan: 'みんなの笑顔と挑戦をぜんぶ載せる新聞！',
      weather: {
        weather: 'sunny',
        maxTemp: 22,
        minTemp: 14,
        phrase: '運動会練習にぴったりのさわやかな風！',
      },
      leadArticle: {
        id: 'lead-school',
        category: '行事特集',
        headline: '白熱のクラス対抗リレー、ついに優勝！',
        subHeadline: '練習の成果を発揮、みんなのバトンがつながった瞬間',
        author: '新聞係 田中＆佐藤',
        content: `先週金曜日に行われた秋季体育祭において、わがたいよう組は見事リレー競技で第一位の栄冠に輝きました！\n\n朝練や放課後のバトンパス練習を何度も重ね、「絶対に落とさない」という合言葉のもと臨んだ本番。アンカーがゴールテープを切った瞬間、クラス席からは大歓声が沸き起こり、担任の先生も目頭を熱くしていました。\n\nキャプテンは「一人ひとりの全力疾走と、ベンチからの大声援があったから勝てた」と満面の笑みで語りました。`,
        imageUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=600&q=80',
        imageCaption: '▲ 力を合わせて掴み取った感動の優勝カップ',
        direction: 'vertical',
      },
      subArticle1: {
        id: 'sub-school-1',
        category: '文化祭速報',
        headline: '合唱曲「虹の彼方に」パート練習開始',
        subHeadline: 'ソプラノとアルトの美しいハーモニーを目指して',
        author: '音楽係',
        content: `来月の文化祭に向けて、合唱コンクールの練習が本格化しています。指揮者の合図に合わせて、教室いっぱいに澄んだ歌声が響いています。`,
        direction: 'vertical',
      },
      subArticle2: {
        id: 'sub-school-2',
        category: 'クラスの日常',
        headline: '花壇のひまわりから種を収穫！',
        subHeadline: '来年の新入生へプレゼントする予定です',
        author: '飼育栽培係',
        content: `夏の間元気に咲いていた大きなひまわりから、ぎっしり詰まった種をたくさん収穫できました。みんなで袋詰め作業を行いました。`,
        direction: 'vertical',
      },
      columnCorner: {
        title: '先生からの一言',
        author: '担任 高橋先生',
        content: `行事を通じて、互いを思いやり助け合う姿がたくさん見られて先生は本当に誇らしいです。秋は勉強も読書も深まる季節。何事にも好奇心をもって挑戦していきましょう！`,
      },
      fourKomaTitle: '休み時間の日常',
      fourKomaFrames: [
        { caption: '① チャイム', text: 'キーンコーンカーンコーン♪' },
        { caption: '② 給食当番', text: '今日の献立は大人気あげパン！' },
        { caption: '③ 余った1個', text: '白熱のじゃんけん大会勃発。' },
        { caption: '④ 勝者', text: '見事に勝ち取ってご満悦の笑顔！' },
      ],
      horoscope: [
        { sign: '今週の給食運', luck: '★★★★★', advice: 'おかわりじゃんけんでチョキを出すと勝率アップ！？' },
      ],
      adText: {
        sponsor: '図書室からのお知らせ',
        catchphrase: '秋の読書週間スタート！',
        subtext: '新着図書がどっさり入荷。本を借りて特製しおりをもらおう！',
      },
      theme: 'craft',
      isGogai: false,
      fontStyle: 'mincho',
    },
  },

  family: {
    name: 'わがやのファミリー新聞（猫ちゃん＆家族）',
    description: 'ペットの可愛い日常、家族の誕生日、旅行の思い出をほのぼの伝える',
    data: {
      paperTitle: 'ねこねこ家庭日報',
      issueNumber: '第 88 号',
      edition: '週末ほっこり版',
      publishDate: '2026年 10月 2日 発行',
      price: '定価 ちゅ〜る 1本',
      publisher: '山田家 編集室 (猫課長主幹)',
      slogan: '家族の笑顔とニャンコのゴロゴロをお届け',
      weather: {
        weather: 'sunny',
        maxTemp: 23,
        minTemp: 15,
        phrase: '陽だまりの窓辺でお昼寝に最高の天気。',
      },
      leadArticle: {
        id: 'lead-family',
        category: '家族トップ',
        headline: '飼い猫「モカ」、新調されたキャットタワーを登頂！',
        subHeadline: '最上階からの見晴らしにご満悦の様子',
        author: '父特派員',
        content: `昨日リビングに設置された最新式木製キャットタワーに対し、警戒を強めていた愛猫モカ（茶トラ・オス3歳）が、今朝ついに自力で最上段のハンモックへ登頂することに成功した。\n\n当初は段ボール箱ばかりに夢中になっていたモカだったが、お気に入りのおもちゃで誘導したところ、軽やかなステップで支柱を駆け上がった。登頂後は窓の外の小鳥を眺めながら優雅に毛づくろいを披露した。\n\n家族一同からは「買ってよかった」「可愛すぎて仕事にならない」との声が相次いでいる。`,
        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
        imageCaption: '▲ 最上階からドヤ顔で下界を見下ろすモカ様',
        direction: 'vertical',
      },
      subArticle1: {
        id: 'sub-family-1',
        category: 'キッチン通信',
        headline: '母特製アップルパイ、大好評のうちに完売',
        subHeadline: '信州産ふじりんごを贅沢に使用',
        author: '母記者',
        content: `秋の恒例行事であるアップルパイ作りが行われ、オーブンから漂うシナモンの香りに誘われて家族全員がリビングに集結。焼き上がり後わずか三十分でホールが空になる人気ぶりだった。`,
        direction: 'vertical',
      },
      subArticle2: {
        id: 'sub-family-2',
        category: '週末予定',
        headline: '今週の日曜日は高原ドライブへ！',
        subHeadline: '紅葉とドッグラン＆カフェ巡りを計画中',
        author: '長女',
        content: `週末は少し足を伸ばして八ヶ岳方面へのドライブが決定。カメラのバッテリーも満タンにして準備万端です。`,
        direction: 'vertical',
      },
      columnCorner: {
        title: 'モカのつぶやき',
        author: 'モカ課長 (代筆:母)',
        content: `人間たちがカリカリの時間を三分遅らせたことを私は忘れていないにゃ。だが今日のブラッシングは実によかった。許してやるにゃ。`,
      },
      fourKomaTitle: 'モカ劇場',
      fourKomaFrames: [
        { caption: '① 箱発見', text: 'Amazonの箱が届いた！' },
        { caption: '② 突撃', text: '本体より箱に一目散にダイブ！' },
        { caption: '③ 収まり', text: 'ぴったりサイズで満足気。' },
        { caption: '④ 爆睡', text: 'そのまま夕方までぐっすりスヤスヤ。' },
      ],
      horoscope: [
        { sign: '今週の運勢', luck: '★★★★★', advice: 'もふもふのお腹に顔をうずめるとストレスが全回復します。' },
      ],
      adText: {
        sponsor: '山田家 晩ごはん相談室',
        catchphrase: '今夜のメニュー募集中！',
        subtext: 'カレー、ハンバーグ、お鍋の三択で多数決を受付中。',
      },
      theme: 'retro',
      isGogai: false,
      fontStyle: 'mincho',
    },
  },
};
